### ISSUE TITLE
How does this compare to xcape?

### ISSUE THREAD

**Issue by louwers** [oblitum/caps2esc#3]
Is there any benefit to using this over [xcape](https://github.com/alols/xcape)?

**Comment by oblitum** [comment]
Benefits are explained in the history section of the README.

**Comment by oblitum** [comment]
My main personal benefit now is that I don't care about the tool anymore, it simply works on my machine and keyboards, I set the service to start on boot on ArchLinux and never have to deal with it again. Previously with xcape + xmodmap I'd lost configuration anytime I connected my bluetooth headphones or closed the lid, or logged off, it was really annoying.

**Comment by oblitum** [comment]
Besides not working on the linux console.

**Comment by louwers** [comment]
Not sure how I missed that. Thank you.
