### ISSUE TITLE
caps2esc causes GNOME to crash

### ISSUE THREAD

**Issue by auscompgeek** [oblitum/caps2esc#6]
🤷‍

**Comment by oblitum** [comment]
Never happened to me, you'll have to provide more details.

**Comment by oblitum** [comment]
For your information, I'm a Gnome user.

**Comment by auscompgeek** [comment]
Are you using Wayland?

**Comment by oblitum** [comment]
No, just X, Wayland still not stable enough for me.

**Comment by auscompgeek** [comment]
Hm. After some more investigation, I think this is a libinput regression, since `libinput-debug-events` also segfaults with caps2esc running…

Oddly enough, xf86-input-libinput works fine.

**Comment by oblitum** [comment]
> Oddly enough, xf86-input-libinput works fine.
It's what I use.

**Comment by oblitum** [comment]
> Oddly enough, xf86-input-libinput works fine.

It's what I use.
